# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GuestLogixTravelCompanion' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GuestLogixTravelCompanion
    pod 'ObjectMapper'
    pod 'SwiftyJSON'

  target 'GuestLogixTravelCompanionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GuestLogixTravelCompanionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
